### ISSUE TITLE
ゼミ論テーマについて再考

### ISSUE THREAD

**Issue by kahorusato** [furuhashilab/sotsuron2020#130]

**Comment by kahorusato** [comment]
ゼミ論テーマ

・「グラフィックレコード」を用いた「聞き書き」の情報活用

昨日新規テーマについて検討したが、ひとまずこれまでのフィールドスタディで得たもの・ゼミ内サークルで得た知見の集大成をまとめる事にする。
理由としては、”せっかく「聞き書き」を行ったので、その情報をきちんと形に残したい”・”グラフィックでまとめることで、「聞き書き」をさらにアップデートできると考えた”からである。

**Comment by kahorusato** [comment]
@mapconcierge 先日ゼミ論テーマについて案出しサポートして頂いたのですが、３年次のゼミ論は、こちらで進めていきたいと考えています🙇‍♀️

**Comment by mapconcierge** [comment]
今まで、聞き書きしたものをグラレコにまとめてみるという理解で合ってる？

**Comment by kahorusato** [comment]
合っています！

**Comment by mapconcierge** [comment]
それでいきましょう！

 「聞き書きｘグラレコ」という記録手法の利点と欠点を明らかにする。

**Comment by kahorusato** [comment]
ありがとうございます！
